spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
     ddl-auto: update

jwt:
  secret: 012345678901234567890123456789012

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
